FROM nginx:1.29.1-alpine-slim

RUN mkdir -p /home/app/tetris
RUN mkdir -p /home/app/tetris_without_sound
RUN mkdir -p /home/app/mario
RUN mkdir -p /home/app/frontend

COPY ./conf.d /etc/nginx/conf.d


# Даем права nginx на чтение файлов
RUN chown -R nginx:nginx /home/app/tetris
RUN chmod -R 755 /home/app/tetris

RUN chown -R nginx:nginx /home/app/tetris_without_sound
RUN chmod -R 755 /home/app/tetris_without_sound

RUN chown -R nginx:nginx /home/app/mario
RUN chmod -R 755 /home/app/mario